#!/bin/bash

if [ "$#" -eq 1 ]; then
    session_name="$1"
else
    # Use fzf to interactively search through existing tmux sessions and all
    # project folders under ~/code.
    session_name=$(
        (tmux list-sessions -F '#{session_name}' ;
        find ~/code -type d -maxdepth 1 -exec basename {} \; ) \
        | sort | uniq | fzf)
fi

if [ -z "$session_name" ]; then
    exit 0
fi

if tmux has-session -t "$session_name" 2>/dev/null; then
    tmux attach-session -t "$session_name"
else
    tmux new-session -s "$session_name"
fi
