window:
  opacity: 0.85
  padding:
    x: 5
    y: 5
  dynamic_padding: false
  decorations: buttonless
  option_as_alt: OnlyLeft

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
  size: 14

env:
  TERM: xterm-256color
